spring:
  application:
    name: sneaker_store

  datasource:
    url: jdbc:postgresql://localhost:5432/sneaker-store-db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sneaker_store

